[package]
name = "jsonrpsee-client-transport"
version = "0.16.2"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "JSON-RPC client transport"
edition = "2021"
license = "MIT"
repository = "https://github.com/paritytech/jsonrpsee"
homepage = "https://github.com/paritytech/jsonrpsee"
documentation = "https://docs.rs/jsonrpsee-client-transport"

[dependencies]
jsonrpsee-core = { path = "../../core", version = "0.16.2", features = ["client"], optional = true }
futures-util = { version = "0.3.14", default-features = false, features = ["alloc"], optional = true }
thiserror = { version = "1", optional = true }
tracing = { version = "0.1.34", optional = true }

futures-channel = { version = "0.3.14", default-features = false, optional = true }
http = { version = "0.2", optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
tokio = { version = "1.16", features = ["net", "time", "macros"], optional = true }
pin-project = { version = "1", optional = true }

# tls
rustls-native-certs = { version = "0.6", optional = true }
webpki-roots = { version = "0.22", optional = true }
tokio-rustls = { version = "0.23", optional = true }

# ws
soketto = { version = "0.7.1", optional = true }

# web-sys
gloo-net = { version = "0.2.6", default-features = false, features = ["json", "websocket"], optional = true }

[features]
native-tls = ["rustls-native-certs", "__tls"]
webpki-tls = ["webpki-roots", "__tls"]

# Internal feature to indicate whether TLS is enabled.
# Does nothing on its own.
__tls = ["tokio-rustls"]

ws = [
    "http",
    "tokio",
    "tokio-util",
    "jsonrpsee-core",
    "futures-util",
    "thiserror",
    "tracing",
    "soketto",
    "pin-project",
]
web = [
    "jsonrpsee-core",
    "futures-util",
    "thiserror",
    "tracing",
    "gloo-net",
    "futures-channel",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
all-features = true
