[package]
name = "jsonrpsee-client-transport"
version = "0.16.3"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "JSON-RPC client transport"
edition = "2021"
license = "MIT"
repository = "https://github.com/paritytech/jsonrpsee"
homepage = "https://github.com/paritytech/jsonrpsee"
documentation = "https://docs.rs/jsonrpsee-client-transport"

[dependencies]
jsonrpsee-types = { path = "../../types", version = "0.16.3", optional = true }
jsonrpsee-core = { path = "../../core", version = "0.16.3", features = ["client"] }
tracing = "0.1.34"

# optional
thiserror = { version = "1", optional = true }
anyhow = { version = "1", optional = true }
futures-channel = { version = "0.3.14", default-features = false, optional = true }
futures-util = { version = "0.3.14", default-features = false, features = ["alloc"], optional = true }
http = { version = "0.2", optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
tokio = { version = "1.16", features = ["net", "time", "macros"], optional = true }
pin-project = { version = "1", optional = true }
rustls-native-certs = { version = "0.6", optional = true }
webpki-roots = { version = "0.25.2", optional = true }
tokio-rustls = { version = "0.24.1", optional = true }
futures-timer = { version = "3", optional = true }

# ws
soketto = { version = "0.7.1", optional = true }

# web-sys
gloo-net = { version = "0.2.0", default-features = false, features = ["json", "websocket"], optional = true }

[features]
tls = ["tokio-rustls", "webpki-roots", "rustls-native-certs"]
ws = [
    "futures-util",
    "http",
    "tokio",
    "tokio-util",
    "soketto",
    "pin-project",
    "jsonrpsee-types",
    "thiserror",
]
web = [
    "gloo-net",
    "futures-channel",
    "futures-timer",
    "futures-util",
    "anyhow",
    "thiserror",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
all-features = true
