language: rust

rust:
  - stable

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
  - cargo build --verbose --no-default-features
  - cargo check --benches --all-features
  # TODO: add this back when the documentation has been updated.
  - RUSTDOCFLAGS="--warn broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items

notifications:
  email:
    on_success: never
    on_failure: never
